language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - scouce@fi.uba.ar
      - hlarrea@fi.uba.ar
      - giuliana.e.altamirano@gmail.com
    on_failure: always
